# Generated by Django 4.0.4 on 2022-07-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='codigoProducto',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='nombre',
        ),
    ]
